/*
 * intdash API specification
 * ## ベースURL  ベースURLは以下のとおりです。APIエンドポイントはこのベースURLから始まります。  ``` https://<host>/api ``` エンドポイント例: ``` https://example.intdash.jp/api/v1/measurements https://example.intdash.jp/api/media/videos ```  ## レスポンスのステータスコード  サーバーからクライアントに返却されるHTTPレスポンスのステータスコードは以下のとおりです。   | コード                    | 説明                                                                  | |:--------------------------|:----------------------------------------------------------------------| | 101 Switching Protocols   | サーバーはプロトコルを切り替えます。                                  | | 200 OK                    | リクエストは成功しました。                                            | | 201 Created               | 新しいリソースが作成されました。                                      | | 204 No Content            | リクエストは成功しました。返却するコンテンツはありません。            | | 400 Bad Request           | 構文が正しくないなどの理由により、リクエストは処理できませんでした。  | | 401 Unauthorized          | リクエストには認証が必要です。                                        | | 403 Forbidden             | アクセス権がないなどの理由により、リクエストは拒否されました。        | | 404 Not Found             | APIまたはリソースが見つかりません。                                   | | 405 Method Not Allowed    | 指定されたメソッドは許可されていません。                              | | 409 Conflict              | 既存のリソースとのコンフリクトのため、リクエストは失敗しました。      | | 500 Internal Server Error | サーバーで予期しないエラーが発生したため、リクエストは失敗しました。  |   ## 注意 リクエストボディのJSONでは、キーの大文字と小文字は区別されません。 従って、以下の2つのリクエストは同じものと見なされます。  ```  {   \"username\" : \"username\",   \"password\" : \"password\" }  ```   ```  {   \"Username\" : \"username\",   \"Password\" : \"password\" }  ```
 *
 * The version of the OpenAPI document: v2.4.0-next-4a4316946
 * Contact: VM2M-support@aptpod.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aptpod.intdash;

import com.aptpod.ApiException;
import org.openapitools.client.model.CreateProjectRequest;
import java.util.Date;
import org.openapitools.client.model.ErrorProblem;
import org.openapitools.client.model.Project;
import org.openapitools.client.model.Projects;
import org.openapitools.client.model.UpdateProjectRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthProjectsApi
 */
@Disabled
public class AuthProjectsApiTest {

    private final AuthProjectsApi api = new AuthProjectsApi();

    /**
     * Create Project
     *
     * プロジェクトを作成します。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createProjectTest() throws ApiException {
        String groupUuid = null;
        CreateProjectRequest createProjectRequest = null;
        Project response = api.createProject(groupUuid, createProjectRequest);
        // TODO: test validations
    }

    /**
     * Delete Project
     *
     * プロジェクトを削除します。プロジェクトを削除できるのはプロジェクトのオーナーのみです。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteProjectTest() throws ApiException {
        String projectUuid = null;
        api.deleteProject(projectUuid);
        // TODO: test validations
    }

    /**
     * Get Project
     *
     * プロジェクトを取得します。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProjectTest() throws ApiException {
        String projectUuid = null;
        Project response = api.getProject(projectUuid);
        // TODO: test validations
    }

    /**
     * List Group Projects
     *
     * プロジェクトのリストを取得します。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listGroupProjectsTest() throws ApiException {
        String groupUuid = null;
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        Projects response = api.listGroupProjects(groupUuid, page, perPage, sort);
        // TODO: test validations
    }

    /**
     * List My Projects
     *
     * 自分（ユーザー）が所属するプロジェクトのリストを取得します。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listMyProjectsTest() throws ApiException {
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        Projects response = api.listMyProjects(page, perPage, sort);
        // TODO: test validations
    }

    /**
     * List Projects
     *
     * プロジェクトのリストを取得します。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listProjectsTest() throws ApiException {
        Date sinceCreatedAt = null;
        Integer page = null;
        Integer perPage = null;
        String sort = null;
        Projects response = api.listProjects(sinceCreatedAt, page, perPage, sort);
        // TODO: test validations
    }

    /**
     * Update Project
     *
     * プロジェクトを更新します。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateProjectTest() throws ApiException {
        String projectUuid = null;
        UpdateProjectRequest updateProjectRequest = null;
        Project response = api.updateProject(projectUuid, updateProjectRequest);
        // TODO: test validations
    }

}
