/*
 * intdash API specification
 * ## ベースURL  ベースURLは以下のとおりです。APIエンドポイントはこのベースURLから始まります。  ``` https://<host>/api ``` エンドポイント例: ``` https://example.intdash.jp/api/v1/measurements https://example.intdash.jp/api/media/videos ```  ## レスポンスのステータスコード  サーバーからクライアントに返却されるHTTPレスポンスのステータスコードは以下のとおりです。   | コード                    | 説明                                                                  | |:--------------------------|:----------------------------------------------------------------------| | 101 Switching Protocols   | サーバーはプロトコルを切り替えます。                                  | | 200 OK                    | リクエストは成功しました。                                            | | 201 Created               | 新しいリソースが作成されました。                                      | | 204 No Content            | リクエストは成功しました。返却するコンテンツはありません。            | | 400 Bad Request           | 構文が正しくないなどの理由により、リクエストは処理できませんでした。  | | 401 Unauthorized          | リクエストには認証が必要です。                                        | | 403 Forbidden             | アクセス権がないなどの理由により、リクエストは拒否されました。        | | 404 Not Found             | APIまたはリソースが見つかりません。                                   | | 405 Method Not Allowed    | 指定されたメソッドは許可されていません。                              | | 409 Conflict              | 既存のリソースとのコンフリクトのため、リクエストは失敗しました。      | | 500 Internal Server Error | サーバーで予期しないエラーが発生したため、リクエストは失敗しました。  |   ## 注意 リクエストボディのJSONでは、キーの大文字と小文字は区別されません。 従って、以下の2つのリクエストは同じものと見なされます。  ```  {   \"username\" : \"username\",   \"password\" : \"password\" }  ```   ```  {   \"Username\" : \"username\",   \"Password\" : \"password\" }  ```
 *
 * The version of the OpenAPI document: v2.4.0-next-4a4316946
 * Contact: VM2M-support@aptpod.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aptpod.intdash;

import com.aptpod.ApiException;
import java.math.BigDecimal;
import org.openapitools.client.model.CreateJobRequest;
import org.openapitools.client.model.ErrorProblemMedia;
import org.openapitools.client.model.Job;
import org.openapitools.client.model.JobList;
import org.openapitools.client.model.JobStatus;
import org.openapitools.client.model.JobType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MediaJobsApi
 */
@Disabled
public class MediaJobsApiTest {

    private final MediaJobsApi api = new MediaJobsApi();

    /**
     * Create Job
     *
     * （Deprecated。代わりに Prefix(&#x60;/projects/00000000-0000-0000-0000-000000000000/&#x60;)が付いたエンドポイントを使用してください） HLSへの変換ジョブを作成します。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createJobTest() throws ApiException {
        CreateJobRequest createJobRequest = null;
        Job response = api.createJob(createJobRequest);
        // TODO: test validations
    }

    /**
     * Create Project Job
     *
     * HLSへの変換ジョブを作成します。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createProjectJobTest() throws ApiException {
        String projectUuid = null;
        CreateJobRequest createJobRequest = null;
        Job response = api.createProjectJob(projectUuid, createJobRequest);
        // TODO: test validations
    }

    /**
     * List Jobs
     *
     * （Deprecated。代わりに Prefix(&#x60;/projects/00000000-0000-0000-0000-000000000000/&#x60;)が付いたエンドポイントを使用してください） HLSへの変換ジョブのリストを取得します。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getJobsTest() throws ApiException {
        List<String> uuid = null;
        List<String> measUuid = null;
        List<JobType> type = null;
        List<JobStatus> status = null;
        BigDecimal limit = null;
        Integer page = null;
        String sort = null;
        String order = null;
        JobList response = api.getJobs(uuid, measUuid, type, status, limit, page, sort, order);
        // TODO: test validations
    }

    /**
     * List Project Jobs
     *
     * HLSへの変換ジョブのリストを取得します。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProjectJobsTest() throws ApiException {
        String projectUuid = null;
        List<String> uuid = null;
        List<String> measUuid = null;
        List<JobType> type = null;
        List<JobStatus> status = null;
        BigDecimal limit = null;
        Integer page = null;
        String sort = null;
        String order = null;
        JobList response = api.getProjectJobs(projectUuid, uuid, measUuid, type, status, limit, page, sort, order);
        // TODO: test validations
    }

}
