/*
 * intdash API specification
 * ## ベースURL  ベースURLは以下のとおりです。APIエンドポイントはこのベースURLから始まります。  ``` https://<host>/api ``` エンドポイント例: ``` https://example.intdash.jp/api/v1/measurements https://example.intdash.jp/api/media/videos ```  ## レスポンスのステータスコード  サーバーからクライアントに返却されるHTTPレスポンスのステータスコードは以下のとおりです。   | コード                    | 説明                                                                  | |:--------------------------|:----------------------------------------------------------------------| | 101 Switching Protocols   | サーバーはプロトコルを切り替えます。                                  | | 200 OK                    | リクエストは成功しました。                                            | | 201 Created               | 新しいリソースが作成されました。                                      | | 204 No Content            | リクエストは成功しました。返却するコンテンツはありません。            | | 400 Bad Request           | 構文が正しくないなどの理由により、リクエストは処理できませんでした。  | | 401 Unauthorized          | リクエストには認証が必要です。                                        | | 403 Forbidden             | アクセス権がないなどの理由により、リクエストは拒否されました。        | | 404 Not Found             | APIまたはリソースが見つかりません。                                   | | 405 Method Not Allowed    | 指定されたメソッドは許可されていません。                              | | 409 Conflict              | 既存のリソースとのコンフリクトのため、リクエストは失敗しました。      | | 500 Internal Server Error | サーバーで予期しないエラーが発生したため、リクエストは失敗しました。  |   ## 注意 リクエストボディのJSONでは、キーの大文字と小文字は区別されません。 従って、以下の2つのリクエストは同じものと見なされます。  ```  {   \"username\" : \"username\",   \"password\" : \"password\" }  ```   ```  {   \"Username\" : \"username\",   \"Password\" : \"password\" }  ```
 *
 * The version of the OpenAPI document: v2.4.0-next-4a4316946
 * Contact: VM2M-support@aptpod.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.aptpod.JSON;

/**
 * SignalConversionOptionNumFixedPoint
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T17:57:54.384855300+09:00[GMT+09:00]")
public class SignalConversionOptionNumFixedPoint {
  public static final String SERIALIZED_NAME_STARTBIT = "startbit";
  @SerializedName(SERIALIZED_NAME_STARTBIT)
  private Integer startbit;

  public static final String SERIALIZED_NAME_BITSIZE = "bitsize";
  @SerializedName(SERIALIZED_NAME_BITSIZE)
  private Integer bitsize;

  /**
   * エンディアン
   */
  @JsonAdapter(EndianEnum.Adapter.class)
  public enum EndianEnum {
    BIG("big"),
    
    LITTLE("little");

    private String value;

    EndianEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EndianEnum fromValue(String value) {
      for (EndianEnum b : EndianEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<EndianEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EndianEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EndianEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return EndianEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ENDIAN = "endian";
  @SerializedName(SERIALIZED_NAME_ENDIAN)
  private EndianEnum endian;

  /**
   * 符号有無
   */
  @JsonAdapter(SignEnum.Adapter.class)
  public enum SignEnum {
    SIGNED("signed"),
    
    UNSIGNED("unsigned");

    private String value;

    SignEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SignEnum fromValue(String value) {
      for (SignEnum b : SignEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SignEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SignEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SignEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SignEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SIGN = "sign";
  @SerializedName(SERIALIZED_NAME_SIGN)
  private SignEnum sign;

  public static final String SERIALIZED_NAME_SCALE = "scale";
  @SerializedName(SERIALIZED_NAME_SCALE)
  private BigDecimal scale;

  public static final String SERIALIZED_NAME_OFFSET = "offset";
  @SerializedName(SERIALIZED_NAME_OFFSET)
  private BigDecimal offset;

  public SignalConversionOptionNumFixedPoint() {
  }

  public SignalConversionOptionNumFixedPoint startbit(Integer startbit) {
    
    this.startbit = startbit;
    return this;
  }

   /**
   * 開始ビット位置
   * @return startbit
  **/
  @javax.annotation.Nonnull
  public Integer getStartbit() {
    return startbit;
  }


  public void setStartbit(Integer startbit) {
    this.startbit = startbit;
  }


  public SignalConversionOptionNumFixedPoint bitsize(Integer bitsize) {
    
    this.bitsize = bitsize;
    return this;
  }

   /**
   * ビットサイズ
   * @return bitsize
  **/
  @javax.annotation.Nonnull
  public Integer getBitsize() {
    return bitsize;
  }


  public void setBitsize(Integer bitsize) {
    this.bitsize = bitsize;
  }


  public SignalConversionOptionNumFixedPoint endian(EndianEnum endian) {
    
    this.endian = endian;
    return this;
  }

   /**
   * エンディアン
   * @return endian
  **/
  @javax.annotation.Nonnull
  public EndianEnum getEndian() {
    return endian;
  }


  public void setEndian(EndianEnum endian) {
    this.endian = endian;
  }


  public SignalConversionOptionNumFixedPoint sign(SignEnum sign) {
    
    this.sign = sign;
    return this;
  }

   /**
   * 符号有無
   * @return sign
  **/
  @javax.annotation.Nonnull
  public SignEnum getSign() {
    return sign;
  }


  public void setSign(SignEnum sign) {
    this.sign = sign;
  }


  public SignalConversionOptionNumFixedPoint scale(BigDecimal scale) {
    
    this.scale = scale;
    return this;
  }

   /**
   * スケールファクター
   * @return scale
  **/
  @javax.annotation.Nonnull
  public BigDecimal getScale() {
    return scale;
  }


  public void setScale(BigDecimal scale) {
    this.scale = scale;
  }


  public SignalConversionOptionNumFixedPoint offset(BigDecimal offset) {
    
    this.offset = offset;
    return this;
  }

   /**
   * オフセット
   * @return offset
  **/
  @javax.annotation.Nonnull
  public BigDecimal getOffset() {
    return offset;
  }


  public void setOffset(BigDecimal offset) {
    this.offset = offset;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SignalConversionOptionNumFixedPoint instance itself
   */
  public SignalConversionOptionNumFixedPoint putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignalConversionOptionNumFixedPoint signalConversionOptionNumFixedPoint = (SignalConversionOptionNumFixedPoint) o;
    return Objects.equals(this.startbit, signalConversionOptionNumFixedPoint.startbit) &&
        Objects.equals(this.bitsize, signalConversionOptionNumFixedPoint.bitsize) &&
        Objects.equals(this.endian, signalConversionOptionNumFixedPoint.endian) &&
        Objects.equals(this.sign, signalConversionOptionNumFixedPoint.sign) &&
        Objects.equals(this.scale, signalConversionOptionNumFixedPoint.scale) &&
        Objects.equals(this.offset, signalConversionOptionNumFixedPoint.offset)&&
        Objects.equals(this.additionalProperties, signalConversionOptionNumFixedPoint.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startbit, bitsize, endian, sign, scale, offset, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignalConversionOptionNumFixedPoint {\n");
    sb.append("    startbit: ").append(toIndentedString(startbit)).append("\n");
    sb.append("    bitsize: ").append(toIndentedString(bitsize)).append("\n");
    sb.append("    endian: ").append(toIndentedString(endian)).append("\n");
    sb.append("    sign: ").append(toIndentedString(sign)).append("\n");
    sb.append("    scale: ").append(toIndentedString(scale)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("startbit");
    openapiFields.add("bitsize");
    openapiFields.add("endian");
    openapiFields.add("sign");
    openapiFields.add("scale");
    openapiFields.add("offset");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("startbit");
    openapiRequiredFields.add("bitsize");
    openapiRequiredFields.add("endian");
    openapiRequiredFields.add("sign");
    openapiRequiredFields.add("scale");
    openapiRequiredFields.add("offset");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SignalConversionOptionNumFixedPoint
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SignalConversionOptionNumFixedPoint.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SignalConversionOptionNumFixedPoint is not found in the empty JSON string", SignalConversionOptionNumFixedPoint.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SignalConversionOptionNumFixedPoint.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("endian").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `endian` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endian").toString()));
      }
      if (!jsonObj.get("sign").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sign` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sign").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SignalConversionOptionNumFixedPoint.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SignalConversionOptionNumFixedPoint' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SignalConversionOptionNumFixedPoint> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SignalConversionOptionNumFixedPoint.class));

       return (TypeAdapter<T>) new TypeAdapter<SignalConversionOptionNumFixedPoint>() {
           @Override
           public void write(JsonWriter out, SignalConversionOptionNumFixedPoint value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SignalConversionOptionNumFixedPoint read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SignalConversionOptionNumFixedPoint instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SignalConversionOptionNumFixedPoint given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SignalConversionOptionNumFixedPoint
  * @throws IOException if the JSON string is invalid with respect to SignalConversionOptionNumFixedPoint
  */
  public static SignalConversionOptionNumFixedPoint fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SignalConversionOptionNumFixedPoint.class);
  }

 /**
  * Convert an instance of SignalConversionOptionNumFixedPoint to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

